backend:
  name: github
  repo: grpaiva/descola-blog
  branch: master # Branch to update (optional; defaults to master)
  site_domain: https://descola-blog.netlify.app/

# local_backend: true
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: post
    label: Posts
    folder: posts
    label_singular: Post
    description: >
      Posts em MD do blog Descola.
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime",
          format: 'DD [de] MMMM [de] YYYY HH:mm' }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Featured Post", name: "featuredPost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
